group 'com.example.com'
version '1.0-SNAPSHOT'

buildscript {
    ext {
        springBootVersion = '2.6.6'
    }
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:1.5.9.RELEASE")
    }
}
apply plugin: 'idea'
apply plugin: 'groovy'
apply plugin: 'java'
apply plugin: 'spring-boot'

sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    implementation('org.springframework.boot:spring-boot-starter-actuator')
    implementation('org.springframework.boot:spring-boot-starter-data-jpa')
    runtimeOnly 'com.h2database:h2'
    implementation('org.projectlombok:lombok:1.18.0')
    implementation('org.apache.httpcomponents:httpclient:4.4')
    implementation('org.springframework.boot:spring-boot-starter-web')
    implementation('org.springframework.boot:spring-boot-starter-logging')
    implementation('org.apache.commons:commons-lang3:3.10')
    annotationProcessor 'org.projectlombok:lombok:1.18.8'


}

wrapper {
    gradleVersion = '4.4'
    distributionUrl = distributionUrl.replace("bin", "all")
}